sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_4e00452ce241_key -iv $encrypted_4e00452ce241_iv -in alpine-tempo-315306-b3852cf22b24.json.enc -out alpine-tempo-315306-b3852cf22b24.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

