sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_4e00452ce241_key -iv $encrypted_4e00452ce241_iv -in alpine-tempo-315306-b3852cf22b24.json.enc -out alpine-tempo-315306-b3852cf22b24.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file alpine-tempo-315306-b3852cf22b24.json
  - gcloud config set project alpine-tempo-315306
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t shubhankergoyal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shubhankergoyal/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
